"""add andar_bahar_rounds

Revision ID: 2487148369c6
Revises: 60f6db391659
Create Date: 2026-08-20 02:09:45.314901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2487148369c6'
down_revision: Union[str, None] = '60f6db391659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('andar_bahar_rounds',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('bet', sa.String(length=6), nullable=False),
    sa.Column('stake', sa.BigInteger(), nullable=False),
    sa.Column('winner', sa.String(length=6), nullable=False),
    sa.Column('payout', sa.BigInteger(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('cards_dealt', sa.Integer(), nullable=False),
    sa.Column('client_seed', sa.String(length=120), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('server_seed', sa.String(length=64), nullable=False),
    sa.Column('server_seed_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_andar_bahar_rounds_user_id'), 'andar_bahar_rounds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_andar_bahar_rounds_user_id'), table_name='andar_bahar_rounds')
    op.drop_table('andar_bahar_rounds')
    # ### end Alembic commands ###
