"""add private tables with join codes

Revision ID: 6df07877bcbc
Revises: eef8534d1a49
Create Date: 2026-08-18 23:07:34.813628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6df07877bcbc'
down_revision: Union[str, None] = 'eef8534d1a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'game_tables',
        sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('game_tables', sa.Column('join_code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_game_tables_join_code'), 'game_tables', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_tables_join_code'), table_name='game_tables')
    op.drop_column('game_tables', 'join_code')
    op.drop_column('game_tables', 'is_private')
    # ### end Alembic commands ###
