"""add pool rummy support

Revision ID: 8f537f6c6eee
Revises: 6df07877bcbc
Create Date: 2026-08-19 11:47:24.514083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f537f6c6eee'
down_revision: Union[str, None] = '6df07877bcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_tables', sa.Column('pool_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_tables', 'pool_limit')
    # ### end Alembic commands ###
